/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/elf_female/scene.gltf --transform --types
Author: enzohao (https://sketchfab.com/enzohao)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/odin-npc-elf-female-cc7ef7c27fe14fb9bb96306e5e5ac608
Title: ODIN_NPC_Elf_female
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.SkinnedMesh;
    Object_8: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_12: THREE.SkinnedMesh;
    Object_14: THREE.SkinnedMesh;
    Object_16: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    NPC_female_body02_021_mat: THREE.MeshStandardMaterial;
    NPC_female_body01_021_mat: THREE.MeshStandardMaterial;
    NPC_female_face_021_mat: THREE.MeshStandardMaterial;
    S_9001_HR_low_mat_2: THREE.MeshStandardMaterial;
    S_9001_HR_hi_mat_2: THREE.MeshStandardMaterial;
    NPC_fmale_eyehair_mat: THREE.MeshStandardMaterial;
  };
};

export function ElfFemale(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/models/elf_female.glb') as GLTFResult;
  return (
    <group
      scale={[0.05, 0.05, 0.05]}
      position={[10, 0, 0]}
      {...props}
      dispose={null}
      receiveShadow={true}
      castShadow={true}
    >
      <primitive object={nodes._rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_6.geometry}
        material={materials.NPC_female_body02_021_mat}
        skeleton={nodes.Object_6.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_8.geometry}
        material={materials.NPC_female_body01_021_mat}
        skeleton={nodes.Object_8.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_10.geometry}
        material={materials.NPC_female_face_021_mat}
        skeleton={nodes.Object_10.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_12.geometry}
        material={materials.S_9001_HR_low_mat_2}
        skeleton={nodes.Object_12.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_14.geometry}
        material={materials.S_9001_HR_hi_mat_2}
        skeleton={nodes.Object_14.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_16.geometry}
        material={materials.NPC_fmale_eyehair_mat}
        skeleton={nodes.Object_16.skeleton}
      />
    </group>
  );
}

useGLTF.preload('/elf_female.glb');
